### ISSUE TITLE
Log cause of failure in authorized keys utility

### ISSUE THREAD

**Issue by ericdand** [GoogleCloudPlatform/guest-oslogin#107]
While testing new functionality, we've got stuck on a mysterious rejection from the `/usr/bin/google_authorized_keys` utility; the PAM module simply logs this as:

    error: AuthorizedKeysCommand /usr/bin/google_authorized_keys ${USERNAME} failed, status 1

The authorized keys module itself seems to do no logging whatsoever: https://github.com/GoogleCloudPlatform/guest-oslogin/blob/master/src/authorized_keys/authorized_keys.cc

Please add logging to the authorized keys utility that indicates where and how it has failed.

**Comment by dorileo** [comment]
I guess we covered most of it with my last PR haven't we?

**Comment by ericdand** [comment]
Yeah, I think your last change did improve this experience; let's see how opaque our errors are now as we start to integrate the change into production, but I think we can close this issue for now.
