### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by rbalint** [GoogleCloudPlatform/guest-oslogin#16]
There is no tagged release since splitting guest-oslogin from compute-image-packages. Please tag a release to help packaging this project.

**Comment by hopkiw** [comment]
Hi @rbalint, we are in the process of automating our software build and release systems, and don't do 'manual' releases for this software. I assume your need for the github release feature is to know when there is some upstream software ready for repackaging by distributions? If so, we plan to use git tags to indicate which commits represent software that has been packaged and released on images we maintain, and distribution maintainers are always welcome to take the latest such tag. You can get a tarball from any version with the URL `https://github.com/<username>/<repository>/tarball/<tag>`. Will that satisfy your needs?

**Comment by rbalint** [comment]
@hopkiw Yes, this is exactly what I'm asking for.

**Comment by rbalint** [comment]
@hopkiw We have been working on compute-image-packages this way with @zmarano for some time.

**Comment by hopkiw** [comment]
How do you think of my suggested alternative to release? i.e. latest github tag + tarball URL ? It should work functionally the same.

**Comment by rbalint** [comment]
@hopkiw That would work, too.

**Comment by rjschwei** [comment]
+1 for the tagging request. I'd prefer not to have some GitHub hash in the tarball name. Due to this being previously part of the guest environment we switched to a date based version format, for example 20190801, but any version numbering for the tarball will work. Having git hashes always generates the impression that things are not backed, which is why I prefer not to have git hashes in the tarball name.

**Comment by hopkiw** [comment]
@rjschwei that's exactly the plan - tags are readable version strings e.g. `20200112.01` and the URL would be e.g. `https://github.com/GoogleCloudPlatform/guest-oslogin/tarball/1:20200112.01`.

**Comment by rbalint** [comment]
@hopkiw I suggest not using the Debian epoch in the tag, nor the version. Using `:` is problematic, this is why it is replaced with % when storing the epoch-ed version as a tag in git: https://dep-team.pages.debian.net/deps/dep14/

**Comment by hopkiw** [comment]
the epoch and `-g1` suffix are both considered packaging artifacts. the version string used in tagging should be e.g. YYYYMMDD.NN
