### ISSUE TITLE
SSH port 22 error 

### ISSUE THREAD

**Issue by jogender2020** [GoogleCloudPlatform/guest-oslogin#32]
I am unable to open SSH through my browser showing port 22 error

**Comment by illfelder** [comment]
Hi, this is more of a generic issue that we typically look at on this repository. Please see https://cloud.google.com/compute/docs/troubleshooting/troubleshooting-ssh or https://cloud.google.com/compute/docs/oslogin/troubleshoot-os-login for troubleshooting help.
