### ISSUE TITLE
google-oslogin-cache service dies on getting groups

### ISSUE THREAD

**Issue by kareem-DA** [GoogleCloudPlatform/guest-oslogin#51]
I am running into a problem on pretty much all of my servers that are running the oslogin service daemon.  I see there is a closed issue (#45) where the groups feature appears to be in alpha at this point and it looks like I am running into an issue related to that.  Right now, when I try to run the oslogin service I am seeing a fail when getting the groups.  

$ sudo systemctl status google-oslogin-cache.service
● google-oslogin-cache.service - NSS cache refresh
   Loaded: loaded (/lib/systemd/system/google-oslogin-cache.service; static; vendor preset: enabled)
   Active: inactive (dead) since Wed 2020-12-16 15:35:18 UTC; 23s ago
  Process: 21022 ExecStart=/usr/bin/google_oslogin_nss_cache (code=exited, status=0/SUCCESS)
 Main PID: 21022 (code=exited, status=0/SUCCESS)

Dec 16 15:35:18 cis-vm-1 systemd[1]: Starting NSS cache refresh...
Dec 16 15:35:18 cis-vm-1 google_oslogin_nss_cache[21022]: oslogin_cache_refresh[21022]: Refreshing passwd entry cache
Dec 16 15:35:18 cis-vm-1 oslogin_cache_refresh[21022]: Refreshing passwd entry cache
Dec 16 15:35:18 cis-vm-1 google_oslogin_nss_cache[21022]: oslogin_cache_refresh[21022]: Refreshing group entry cache
Dec 16 15:35:18 cis-vm-1 oslogin_cache_refresh[21022]: Refreshing group entry cache
Dec 16 15:35:18 cis-vm-1 google_oslogin_nss_cache[21022]: oslogin_cache_refresh[21022]: Failure getting groups, quitting
Dec 16 15:35:18 cis-vm-1 google_oslogin_nss_cache[21022]: oslogin_cache_refresh[21022]: Produced empty group cache file, removing /etc/oslogin_group.cache.bak.
Dec 16 15:35:18 cis-vm-1 oslogin_cache_refresh[21022]: Failure getting groups, quitting
Dec 16 15:35:18 cis-vm-1 oslogin_cache_refresh[21022]: Produced empty group cache file, removing /etc/oslogin_group.cache.bak.
Dec 16 15:35:18 cis-vm-1 systemd[1]: Started NSS cache refresh.

Looking at the code, I see that the service is running the following metatdata query and getting and empty response.  Looks like the service
$ curl -H "Metadata-Flavor: Google"  "http://metadata.google.internal/computeMetadata/v1/oslogin/groups?pagesize=10"
{"nextPageToken":"0"}

On line 249
    if (!HttpGet(url.str(), &response, &http_code) || http_code != 200 ||
        response.empty() || !LoadJsonGroupsToCache(response)) {
      *errnop = ENOENT;
      return false;
    }

the empty response throws an errors and the process dies...

Am I missing something?

Version of google-compute-engine-oslogin I am running
$ dpkg-query --list |grep oslog
ii  google-compute-engine-oslogin      20200925.00-0ubuntu3~18.04.0                amd64        Google Compute Engine OS Login

**Comment by illfelder** [comment]
The error you're seeing is nothing to be concerned by. We have a separate issue filed - #50 - to fix the concerning logging messages when the metadata server returns no results.
