### ISSUE TITLE
Question: Using OS Login from a Bastion for SSH + IAP inside a chroot to second VM in a different project

### ISSUE THREAD

**Issue by ranjitk-burwood** [GoogleCloudPlatform/guest-oslogin#67]
Hello, a bit of a longwinded question but what I am attempting to achieve is the ability to have a Bastion Host in one GCP project connect via SSH to the internal IP of another VM in a different project. At the moment I cannot use `gcloud compute ssh` and can only use `ssh` from `/bin/ssh`. Additionally I cannot use a shared VPC setup and need networking on both projects to be independent of one another.

In a testing environment outside of a chroot I was able to successfully get a `gcloud compute ssh` connection across two VMs using their internal IPs across projects. The command used the `--tunnel-through-iap` flag.

Did this only work because of the `--tunnel-through-iap` flag which sets up TCP forwarding? I guess I am a bit confused on how this works overall and is there a way to replicate it with the normal `ssh` command? How exactly does `gcloud compute ssh <INSTANCE> --zone=<ZONE> --tunnel-through-iap --project=<PROJECT_ID>` translate into a `ssh` command?

If there is a better GitHub repository to post this issue at let me know.

**Comment by illfelder** [comment]
This seems like a good question for the [GCE Discussion forum](https://groups.google.com/g/gce-discussion).

In general, gcloud uses the open source SSH client installed on a user's machine, so you should be able to replicate its logic. If you have a place where you can run gcloud, you can view the commands gcloud executes by adding the flags `--log-http --verbosity=debug` (note, there will likely be a lot of output so you may want to try `--log-http` first).
