### ISSUE TITLE
support configurable metadata server address

### ISSUE THREAD

**Issue by t33m** [GoogleCloudPlatform/guest-oslogin#71]
It would be useful to make the address of the metadata service configurable for testing purpose or for proxying requests through http caching proxy or custom http filters. For NSS libs metadata server address can be passed with configuration file, for PAM modules as [PAM Module argument](https://www-uxsup.csx.cam.ac.uk/pub/doc/redhat/redhat7.3/rhl-rg-en-7.3/s1-pam-arguments.html) and for google_authorized_keys as a command line flag.

**Comment by hopkiw** [comment]
Configurable address is intentionally not permitted for security reasons. There should also be no need for a proxy to the metadata server, as it is link-local to the VM. For testing, you should compile an alternative.
