### ISSUE TITLE
Ability to operate outside of GCP

### ISSUE THREAD

**Issue by artooro** [GoogleCloudPlatform/guest-oslogin#72]
We have servers on GCE and on various other environments as well.
I would be nice to be able to centralize the Identity and Access to our Google Cloud Identity using IAM and OS Login.

There currently isn't a Google solution for this, and it seems a natural progression just like Windows has GCPW we also need GCPL (for Linux) and OS Login would be perfect if it could have an option to work outside of the GCP network.

**Comment by hopkiw** [comment]
Currently, OS Login is not planned for on-prem use, but I will forward this on to Google's product team. Since this repository is for managing the code components that enable OS Login, and not for discussion of Google's services or plans, I will close this issue.
